### PR TITLE
Fix facebook feed

### LINKED ISSUE #17: Fix Facebook feed

### PR DESCRIPTION
**Pull request by tobidalhof**
currently blocked by #15 

closes #17

### CODE REVIEW

File: src/sites/facebook.ts [hunk 1]
```diff
@@ -14,18 +14,18 @@ const facebook = new Site({
       validateUrl: url => url.pathname === '/',
       requiredUserConfigKey: UserConfigKey.FacebookHideHomeFeed,
       injectCss: `
-        div[role="feed"] {
+        #ssrb_feed_start + div {
```
Comment (arfizato) [inline src/sites/facebook.ts:17]: doesn't work anymore @tobiasdalhof . at least for me it's 
`div[role="main"]{`

**Review by arfizato — COMMENTED** [review]
doesn't work on facebook feed

File: src/sites/facebook.ts (hunk 1 above)
Comment (tobiasdalhof) [reply src/sites/facebook.ts:17]: Using `div[role="main"]` seems to work, but it has the unintended side effect of removing the create post form. To address this, we could consider using a list of selectors and prioritize them, with `div[role="main"]` as the last selector in case others fail

**Comment by tobiasdalhof** [comment]
> doesn't work on facebook feed

@arfizato I'll open a new PR later
